// content2.js — Chương 3–7 + Tài liệu tham khảo (đẩy tiếp vào body chung)
const L = require('./lib.js');
const { push } = require('./content1.js');
const {
  Paragraph, TextRun, PageBreak, AlignmentType, BorderStyle, ShadingType,
  P, runs, H1, H2, H3, bullet, numItem, code, img, table, ACCENT
} = { ...require('docx'), ...L };

// ============================ CH3: KIẾN TRÚC & THIẾT KẾ ============================
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("3. Kiến trúc và quyết định thiết kế"),
  H2("3.1. Sơ đồ khối tổng thể"),
  P("Đường ống (pipeline) gồm bốn tầng nối tiếp:"),
  code("Tausworthe URNG → [Fr ROM, G ROM] → Box-Muller core → CLT accumulator → N(0,1)"),
  P("Mỗi chu kỳ, URNG sinh một từ 32-bit. Box-Muller core trích các trường bit từ từ này để tra hai ROM, nhân và làm tròn tạo một mẫu Box-Muller. CLT accumulator gom A=4 mẫu liên tiếp thành một mẫu nhiễu đầu ra. Thông lượng do đó là 1/A = 0,25 mẫu/chu kỳ."),
  H2("3.2. Tham số thiết kế (theo Boutillon Table 1)"),
  table([
    ["Tham số","Ký hiệu","Giá trị","Ý nghĩa"],
    ["Bit phân số đầu ra","B","6","Định dạng Q(_.6)"],
    ["Số mức phân vùng Fr","K","5","Độ dài đuôi ≈ ±4σ"],
    ["Bit phân số Fr","m","7","Độ phân giải bảng Fr"],
    ["Offset Fr","δ","0,467","Tâm đoạn con"],
    ["Bit phân số G","m'","7","Độ phân giải bảng G"],
    ["Offset G","δ'","0,5","Tâm đoạn con cosine"],
    ["Hệ số tích lũy CLT","A","4","std=√A=2 → dịch 1 bit"],
    ["Bậc URNG","k₁,k₂,k₃","31,29,28","Chu kỳ ≈ 2⁸⁸"],
  ], [2600, 1500, 1600, 3060]),
  H2("3.3. Bảy quyết định thiết kế chính"),
  P("Các lựa chọn dưới đây được ghi nhận để bảo vệ thiết kế:"),
  numItem("B=6: điểm cân bằng giữa độ chính xác và tài nguyên. B nhỏ (4) gây 'răng lược' rõ; B lớn (8–10) tăng dung lượng ROM và độ rộng nhân không cần thiết. (Xem khảo sát ở mục 5.6.)"),
  numItem("A=4: std=√A=2=2¹ nên chuẩn hóa chỉ cần dịch phải 1 bit (miễn phí trong phần cứng), đồng thời đủ làm mượt sai số lượng tử."),
  numItem("Round-half-up: đơn giản trong Verilog, độ chệch được CLT bù, đảm bảo khớp bit MATLAB↔RTL."),
  numItem("Ràng buộc seed (s1>1, s2>7, s3>15): tránh trạng thái suy biến của LFSR sau khi áp mặt nạ."),
  numItem("Phân vùng đệ quy Fr (K=5): 'zoom' vào vùng x→0 nơi f(x) biến thiên mạnh, đạt đuôi ±4σ với tổng ROM chỉ 90 byte."),
  numItem("G ROM 256 từ: tận dụng đối xứng cosine, chỉ lưu 1/4 chu kỳ; hệ số √2 để khớp dạng Box-Muller."),
  numItem("Đồng mô phỏng bit-accurate: dùng mô hình MATLAB dấu phẩy tĩnh làm golden, so khớp từng mẫu để phát hiện sai sót (làm tròn, dấu, pipeline) nhanh hơn nhiều so với dò trên waveform."),
  H2("3.4. Phân tích độ rộng bit"),
  P("Khi hiện thực ROM thực tế, độ rộng từ được kiểm tra lại so với tài liệu gốc. Có một điểm thú vị liên quan đến sai khác √2 (xem chương 7):"),
  bullet("Bảng Fr (đã sửa về √(−ln x) theo Boutillon eq.(1)): giá trị lớn nhất là 470, vừa khít 9 bit không dấu (đúng 2+m=9 như tài liệu). Lưu ý: công thức sai √(−2 ln x) trước đó = √2·√(−ln x) đã thổi Fr max lên 665, khiến tưởng nhầm cần 10 bit — đây thực chất là triệu chứng của lỗi √2."),
  bullet("Bảng G: |G| lớn nhất là 181 = √2·128, cần 9 bit có dấu (tài liệu ghi 1+m'=8 bit chỉ chứa tối đa ±127, không đủ). Đây là sai khác độ rộng bit thực sự duy nhất. Bảng dữ liệu G phải được sinh ở dạng bù-2 9 bit để giá trị âm nạp đúng dấu."),
  P("Đây là ví dụ điển hình cho thấy giá trị của kiểm chứng định lượng: sai sót độ rộng bit (và cả lỗi √2 ẩn sau nó) không lộ trên sơ đồ khối nhưng sẽ gây tràn/sai dấu nếu không phát hiện sớm. Cả hai đã được xử lý trong mã bàn giao (RTL dùng FR_W=9, G_W=9).", { after:160 }),
);

// ============================ CH4: TRIỂN KHAI RTL ============================
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("4. Triển khai RTL Verilog"),
  H2("4.1. Các module"),
  P("RTL gồm bảy module, mỗi module khớp bit-by-bit với một hàm MATLAB golden tương ứng:"),
  table([
    ["Module","Vai trò","Golden MATLAB","Độ rộng chính"],
    ["taus_urng.v","URNG Tausworthe tổ hợp (3×LFSR)","taus_urng_fixed.m","32 bit"],
    ["lzc32.v","Đếm số bit 0 dẫn đầu (leading zeros)","vòng đếm trong box_muller_fixed.m","0..32"],
    ["fr_rom.v","Bảng Fr, K=5×16 = 80 từ","fr_rom_gen.m","FR_W=9 (Q2.7)"],
    ["g_rom.v","Bảng G, 256 từ có dấu","g_rom_gen.m","G_W=9 (Q1.7)"],
    ["bm_core.v","Trích bit→tra ROM→nhân→làm tròn→dấu","box_muller_fixed.m","tích 20b, ra 16b"],
    ["clt_acc.v","Tích lũy A=4 + bù trung bình + chuẩn hóa","clt_acc_fixed.m","ra 16b (Q2.6)"],
    ["awgn_top.v","Ghép toàn bộ pipeline","awgn_fixed_top.m","—"],
  ], [1500, 3100, 2560, 1600]),
  H2("4.2. Một số chi tiết hiện thực then chốt"),
  H3("4.2.1. Trích trường bit trong Box-Muller"),
  P("Từ từ URNG 32-bit, lõi Box-Muller đếm số bit 0 dẫn đầu (lz) rồi suy ra mức phân vùng và các chỉ số:"),
  code("r_idx = min(lz>>2, K−1);   s_start = 28 − r_idx·4;\ns = (urng >> s_start) & 0xF;   s' = urng[7:0];   sign = urng[8];"),
  P("Điểm tinh tế: mô hình MATLAB đếm leading zeros trên cả 32 bit (không theo phần chú thích trong mã). RTL được viết để khớp chính xác hành vi mã MATLAB thực thi, không khớp theo chú thích — đây là nguyên tắc 'golden là mã chạy, không phải tài liệu'."),
  H3("4.2.2. Làm tròn và áp dấu"),
  P("Sau khi nhân Fr×G (định dạng Q3.14), kết quả được làm tròn về Q(_.B) bằng dịch phải m+m'−B = 8 bit theo round-half-up, rồi áp dấu theo phương trình (7) của Boutillon:"),
  code("P_round = (P + 128) >>> 8;   // arithmetic shift = ⌊(P+128)/256⌋\nn = (sign==0) ? P_round : (−P_round − 1);   // bù-1 để dời trung bình"),
  P("Phép cộng nửa LSB rồi dịch số học đã được kiểm chứng cho kết quả trùng khít ⌊·⌋ của MATLAB trên toàn dải số có dấu (kiểm tra ±200000, 0 sai lệch). Việc áp dấu kiểu bù-1 (−P−1 thay vì −P) tạo độ chệch trung bình −2^(−B−1) mà CLT sẽ bù lại."),
  H2("4.3. Kết quả đồng mô phỏng bit-accurate"),
  P("Ba testbench được xây dựng, dùng golden vectors sinh từ mô hình bit-exact. Toàn bộ đều khớp tuyệt đối:"),
  table([
    ["Testbench","Phạm vi kiểm tra","Số mẫu","Kết quả"],
    ["tb_urng","URNG so với golden_urng","8000","0 sai lệch — PASS"],
    ["tb_awgn_datapath","Box-Muller + CLT so với golden","8000 + 2000","0 sai lệch — PASS"],
    ["tb_awgn_top","Pipeline đầy đủ, URNG tự sinh","2000","0 sai lệch — PASS"],
  ], [2400, 3260, 1700, 2000]),
  P("Kết quả 0 sai lệch trên cả ba mức (thành phần, đường dữ liệu, và tích hợp) khẳng định RTL hiện thực đúng 100% so với mô hình tham chiếu, sẵn sàng cho tổng hợp.", { after:160 }),
);

// ============================ CH5: KẾT QUẢ MÔ PHỎNG (40%) ============================
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("5. Kết quả mô phỏng và kiểm chứng thống kê"),
  P("Chương này kiểm chứng chất lượng thống kê của nhiễu sinh ra. Dữ liệu được tạo bằng mô hình dấu phẩy tĩnh bit-exact (cùng kết quả với RTL đã đồng mô phỏng), với N = 300.000 mẫu cho các kiểm định phân bố và 1.000.000 mẫu cho mô phỏng BER. Các phép đo dùng cấu hình Fr = √(−ln x) theo Boutillon eq.(1) để đạt std = 1 (xem chương 7 về sai khác phát hiện)."),
  H2("5.1. Mô-men thống kê"),
  P("Bốn mô-men đầu của phân bố đầu ra so với N(0,1) lý tưởng:"),
  table([
    ["Đại lượng","Lý tưởng N(0,1)","Đo được","Nhận xét"],
    ["Trung bình (mean)","0","+0,0039","≈ 0 ✓"],
    ["Độ lệch chuẩn (std)","1","1,0084","≈ 1 ✓"],
    ["Độ xiên (skewness)","0","+0,0055","đối xứng ✓"],
    ["Độ nhọn (kurtosis)","3","2,975","≈ 3 ✓"],
  ], [2400, 2300, 1860, 2800]),
  P("Cả bốn mô-men đều rất sát giá trị lý tưởng (sai lệch < 1%), xác nhận hình dạng tổng thể là Gauss chuẩn."),
  H2("5.2. Histogram và phân bố"),
  P("Hình 5.1 so sánh histogram nhiễu fixed-point (đã chuẩn hóa về σ=1) với hàm mật độ N(0,1). Hai cấu hình Fr được trình bày: bản đúng theo Boutillon eq.(1) cho std=1, và bản theo mã hiện tại cho std=√2 (sau chuẩn hóa, hình dạng trùng nhau)."),
  ...img("fig1_histogram.png", 600, 222, "Hình 5.1. Histogram nhiễu fixed-point so với N(0,1) lý tưởng."),
  P("Đường histogram bám sát đường lý tưởng. Quan sát kỹ gần đỉnh thấy vài 'gai' mảnh — đây là hiệu ứng răng lược (comb) do đầu ra rời rạc theo bội số 1/64 (B=6), sẽ phân tích định lượng ở mục 5.5–5.6."),
  H2("5.3. Đuôi phân bố và Q-Q plot"),
  P("Hình 5.2 vẽ phân bố trên thang log để kiểm tra đuôi đến ±4σ; Hình 5.3 là đồ thị Q-Q so quantile mẫu với quantile lý thuyết."),
  ...img("fig2_tail_logscale.png", 460, 307, "Hình 5.2. Đuôi phân bố trên thang logarit (đến ±4σ)."),
  ...img("fig3_qqplot.png", 360, 360, "Hình 5.3. Đồ thị Q-Q: quantile mẫu so với N(0,1)."),
  P("Đuôi phân bố bám đường lý tưởng đến khoảng ±4σ rồi thưa dần do số mức phân vùng K=5 và số mẫu hữu hạn. Trên Q-Q plot, các điểm nằm sát đường y=x trong dải trung tâm, lệch nhẹ ở hai đầu mút — đặc trưng của phân bố lượng tử có đuôi hữu hạn."),
  H2("5.4. Phổ công suất và tự tương quan"),
  P("Tính 'trắng' của nhiễu được kiểm tra qua mật độ phổ công suất (PSD, ước lượng Welch) và hàm tự tương quan."),
  ...img("fig4_psd.png", 500, 312, "Hình 5.4. Mật độ phổ công suất — kiểm tra phổ phẳng (white)."),
  ...img("fig5_autocorr.png", 500, 312, "Hình 5.5. Hàm tự tương quan chuẩn hóa (lag 0..50)."),
  P("PSD dao động quanh một mức không đổi (≈ 3 dB/Hz), phần lớn nằm trong ±1,5 dB — phổ phẳng, không có cấu trúc tần số (các điểm trũng tại DC và Nyquist là tự nhiên do đã trừ trung bình và hiệu ứng biên). Hàm tự tương quan có đỉnh duy nhất tại lag 0; chỉ 3/50 lag vượt nhẹ ngưỡng tin cậy 95% (kỳ vọng ngẫu nhiên ≈ 2,5/50), xác nhận các mẫu độc lập (i.i.d., nhiễu trắng)."),
  H2("5.5. Kiểm định mức độ phù hợp (goodness-of-fit)"),
  P("Mức độ phù hợp với N(0,1) được đánh giá bằng nhiều thước đo:"),
  table([
    ["Thước đo","Giá trị","Diễn giải"],
    ["KS distance D","0,494%","Sai lệch CDF lớn nhất — rất nhỏ"],
    ["Sai số PDF bulk (|z|<3), trung bình","2,93%","Do răng lược B=6"],
    ["Sai số PDF bulk (|z|<3), lớn nhất","13,87%","Tại bin hẹp bị răng lược"],
    ["χ² (N=8000)","57,6 (dof=33), p=0,005","Nhạy với rời rạc hóa"],
    ["χ² (N=300000)","603 (dof=45), p≈0","Quá nhạy ở N lớn"],
  ], [3200, 2400, 2860]),
  P("Cần lưu ý về kiểm định χ²: ở số mẫu lớn, χ² và Kolmogorov–Smirnov trở nên cực nhạy và sẽ bác bỏ giả thuyết Gauss với bất kỳ phân bố rời rạc nào, vì đầu ra lượng tử B=6 (bội số 1/64) về bản chất không thể trùng khít một phân bố liên tục. Do đó các tài liệu phần cứng (Boutillon, Lee) báo cáo bằng sai số tương đối PDF và khoảng cách phân bố thay vì p-value. Ở đây KS distance chỉ 0,494% và các mô-men sai lệch < 1% là bằng chứng thuyết phục rằng hình dạng tổng thể rất gần Gauss; sai số PDF theo từng bin hẹp (~3% trung bình) phản ánh hiệu ứng răng lược chứ không phải sai lệch hình dạng vĩ mô."),
  H2("5.6. Khảo sát độ rộng bit (chứng minh B=6)"),
  P("Để biện minh cho lựa chọn B=6, ta quét B ∈ {4, 6, 8, 10} (giữ m=m'=7) và đo sai số phân bố cùng số mức lượng tử:"),
  table([
    ["B","Sai số PDF bulk (%)","KS (%)","Số mức rời rạc"],
    ["4","8,15","1,743","134"],
    ["6","3,42","0,465","495"],
    ["8","2,61","0,175","1818"],
    ["10","2,52","0,158","6363"],
  ], [1400, 3200, 1800, 2060]),
  ...img("fig8_bitwidth.png", 480, 330, "Hình 5.6. Đánh đổi độ chính xác theo độ rộng bit B."),
  P("Từ B=4 lên B=6, sai số giảm mạnh (KS 1,74% → 0,47%). Từ B=6 trở đi, cải thiện sai số PDF nhỏ dần (3,42% → 2,61% → 2,52%) trong khi số mức và độ rộng đầu ra tăng nhanh; tồn tại 'sàn' sai số ~2,5% do hiệu ứng răng lược và độ phân giải ROM (m=m'=7). Do đó B=6 là điểm cân bằng tốt giữa độ chính xác và tài nguyên, phù hợp Bảng 1 của Boutillon."),
  H2("5.7. Mô phỏng BER (kiểm chứng ứng dụng)"),
  P("Phép kiểm chứng quyết định nhất là dựng đường BER cho điều chế BPSK và QPSK qua kênh AWGN dùng chính nhiễu fixed-point, rồi so với lý thuyết Q(√(2·Eb/N0)). Nhiễu được chuẩn hóa về phương sai đơn vị rồi nhân hệ số σ tương ứng từng mức Eb/N0."),
  ...img("fig6_ber_bpsk.png", 470, 345, "Hình 5.7. Đường BER BPSK: fixed-point so với lý thuyết và randn lý tưởng."),
  ...img("fig7_ber_qpsk.png", 600, 254, "Hình 5.8. BER QPSK (Gray) và chòm sao tín hiệu @ Eb/N0=6 dB."),
  P("Bảng dưới liệt kê BER theo Eb/N0:"),
  table([
    ["Eb/N0 (dB)","Lý thuyết","BPSK fixed","QPSK fixed"],
    ["0","7,9×10⁻²","7,9×10⁻²","7,8×10⁻²"],
    ["2","3,8×10⁻²","3,8×10⁻²","3,8×10⁻²"],
    ["4","1,25×10⁻²","1,23×10⁻²","1,23×10⁻²"],
    ["6","2,4×10⁻³","2,3×10⁻³","2,3×10⁻³"],
    ["8","1,9×10⁻⁴","1,7×10⁻⁴","1,6×10⁻⁴"],
  ], [2200, 2400, 1930, 1930]),
  P("Đường BER của nhiễu fixed-point trùng khít đường lý thuyết suốt dải 0–9 dB và ngang với nhiễu randn lý tưởng. Tỉ số BER(fixed)/BER(lý thuyết) trong vùng tin cậy (BER>5×10⁻⁵) có trung bình 0,97 (khoảng 0,89–1,02). Đây là bằng chứng mạnh nhất: bất chấp hiệu ứng răng lược ở mức histogram, hành vi BER trong hệ thống truyền thông thực tế là chính xác — đúng mục tiêu của bộ sinh nhiễu cho channel emulation.", { after:160 }),
);

// ============================ CH6: TỔNG HỢP FPGA ============================
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("6. Tổng hợp FPGA (ước lượng)"),
  P("Phần này cung cấp kịch bản tổng hợp sẵn sàng chạy và ước lượng tài nguyên phân tích. Số liệu chính xác cần chạy Vivado (script build.tcl sinh các báo cáo utilization/timing/power); ước lượng dưới đây để định cỡ và đối chiếu."),
  H2("6.1. Ước lượng tài nguyên theo module"),
  table([
    ["Module","LUT","FF","DSP","BRAM"],
    ["taus_urng","~90","96","0","0"],
    ["lzc32","~35","0","0","0"],
    ["fr_rom","~20","0","0","0/1"],
    ["g_rom","~30","0","0","0/1"],
    ["bm_core","~60","16","1","0"],
    ["clt_acc","~40","38","0","0"],
    ["Tổng (ROM phân tán)","~280","~150","1","0"],
  ], [3000, 1640, 1640, 1240, 1240]),
  P("Bảng Fr (800 bit) và G (2304 bit) rất nhỏ nên thường được suy ra thành ROM phân tán (dùng LUT) thay vì BRAM; tùy phiên bản công cụ có thể ra 0 hoặc 2 khối BRAM18 — cả hai đều chấp nhận được."),
  H2("6.2. Đối chiếu với thiết kế tham khảo"),
  table([
    ["Thiết kế","Phương pháp","LUT","FF","DSP","BRAM"],
    ["Đồ án này (ước lượng)","Box-Muller + CLT (LUT)","~280","~150","1","0–2"],
    ["Lee 2006 (đo thực)","Box-Muller (log/√/sincos)","1272","380","17","3"],
  ], [2900, 2700, 1100, 900, 800, 960]),
  P("Phương pháp Boutillon dựa trên bảng tra Fr/G rẻ hơn khoảng 4–5 lần về LUT và ~17 lần về DSP so với phương pháp Lee 2006 (dùng xấp xỉ Chebyshev và CORDIC), đúng như kỳ vọng. Đây là ưu thế chính của kiến trúc LUT-based cho các bộ sinh nhiễu thông lượng vừa phải."),
  H2("6.3. Định thời và thông lượng"),
  bullet("Đường tới hạn dự kiến ở bm_core (nhân 1 DSP + cộng làm tròn + áp dấu + bão hòa) hoặc đường ROM→nhân; ước ~6–10 ns → Fmax khoảng 100–150 MHz."),
  bullet("Mục tiêu xung nhịp 50 MHz có biên định thời lớn. Thông lượng = 1/A = 0,25 mẫu/chu kỳ → 12,5 MS/s ở 50 MHz (vượt mục tiêu 10 MHz); 25 MS/s ở 100 MHz."),
  bullet("Nếu cần Fmax cao hơn, có thể chia bm_core thành 3 tầng pipeline (ROM-read / nhân / làm tròn-dấu-bão hòa); clt_acc đã gom theo tín hiệu bm_valid nên không phụ thuộc độ trễ cố định.", 0),
  new Paragraph({ spacing:{after:160}, children:[new TextRun("")] }),
);

// ============================ CH7: KẾT LUẬN ============================
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("7. Kết luận và hướng phát triển"),
  H2("7.1. Kết quả đạt được"),
  bullet("Hoàn thành mô hình MATLAB (dấu phẩy động và dấu phẩy tĩnh) và RTL Verilog đầy đủ cho bộ sinh AWGN theo phương pháp Boutillon."),
  bullet("Đồng mô phỏng bit-accurate đạt 0 sai lệch trên cả ba mức (thành phần, đường dữ liệu, tích hợp) với 8000 mẫu URNG/BM và 2000 mẫu đầu ra."),
  bullet("Kiểm chứng thống kê đầy đủ: mô-men sai lệch < 1%, KS distance 0,494%, phổ phẳng, nhiễu trắng."),
  bullet("Đường BER BPSK/QPSK trùng khít lý thuyết (tỉ số trung bình 0,97), chứng minh tính đúng đắn cho ứng dụng channel emulation."),
  bullet("Khảo sát độ rộng bit khẳng định B=6 là điểm cân bằng; ước lượng tài nguyên cho thấy ưu thế ~4–5× LUT và ~17× DSP so với Lee 2006."),
  H2("7.2. Hai sai khác đã phát hiện và khắc phục"),
  P("Trong quá trình kiểm chứng, phát hiện hai điểm trong mô hình MATLAB ban đầu, đều đã được sửa trong mã bàn giao:"),
  P("Thứ nhất — hệ số √2: bộ sinh bảng Fr (fr_rom_gen.m) tính theo √(−2 ln x), trong khi bảng G đã chứa sẵn hệ số √2. Khi nhân hai bảng, kết quả trở thành √2 · N(0,1), tức độ lệch chuẩn đầu ra ≈ √2 ≈ 1,42 thay vì 1. Theo Boutillon phương trình (1), công thức đúng là f(x₁) = √(−ln x₁); khi đó f·g = √(−2 ln x₁)·cos(2π x₂) cho đúng N(0,1). Đã sửa fr_rom_gen.m thành √(−ln x); kiểm chứng lại cho std = 0,998, skew ≈ 0, kurtosis ≈ 2,98. RTL không đổi (chỉ là dữ liệu ROM). Một hệ quả thú vị: lỗi √2 đồng thời thổi phồng giá trị Fr lên √2 lần (max 665 thay vì 470), khiến tưởng nhầm Fr cần 10 bit; sau khi sửa, Fr vừa khít 9 bit đúng như tài liệu."),
  P("Thứ hai — độ rộng từ bảng G: g_rom_gen.m đặt word_bits = 1+m' = 8, trong khi |G|max = √2·128 = 181 > 127 nên cần 9 bit có dấu. Với 8 bit, các giá trị G âm bị mã hóa bù-2 sai dấu khi ghi ra file ROM. Đã sửa word_bits = 9; bộ đồng mô phỏng sau khi sửa khớp 100% (0 sai lệch) ở cả ba mức kiểm tra."),
  P("Lưu ý rằng với ứng dụng channel emulation, nhiễu luôn được chuẩn hóa về công suất mục tiêu theo từng mức Eb/N0, nên hệ số √2 không ảnh hưởng kết quả BER; tuy vậy việc sửa giúp mô hình nhất quán với lý thuyết và với tài liệu thiết kế."),
  H2("7.3. Hướng phát triển"),
  bullet("Chạy tổng hợp Vivado thực tế để thu số liệu tài nguyên/định thời chính xác và kiểm chứng ước lượng."),
  bullet("Pipeline hóa bm_core để nâng Fmax; bọc giao tiếp AXI-Stream để tích hợp hệ thống."),
  bullet("Tăng K (số mức phân vùng) để kéo dài đuôi phân bố đến ±6σ phục vụ đo BER ở mức 10⁻¹²."),
  bullet("Xây dựng bộ mô phỏng kênh AWGN hoàn chỉnh (cộng nhiễu vào tín hiệu điều chế) và demo trên board FPGA."),
);

// ============================ TÀI LIỆU THAM KHẢO ============================
const ref = (t) => new Paragraph({ numbering:{reference:"r", level:0}, spacing:{after:100, line:264}, children:[new TextRun({ text:t, size:20 })] });
push(
  new Paragraph({ children:[new PageBreak()] }),
  H1("Tài liệu tham khảo"),
  ref("E. Boutillon, J.-L. Danger, A. Ghazel. \"Design of high speed AWGN communication channel emulator.\" Analog Integrated Circuits and Signal Processing / ICECS, 2000."),
  ref("D.-U. Lee, W. Luk, J. D. Villasenor, P. Y. K. Cheung. \"A Hardware Gaussian Noise Generator Using the Box-Muller Method and Its Error Analysis.\" IEEE Transactions on Computers, vol. 55, no. 6, 2006."),
  ref("P. L'Ecuyer. \"Maximally Equidistributed Combined Tausworthe Generators.\" Mathematics of Computation, vol. 65, no. 213, 1996."),
  ref("S. Malik, A. Hemani. \"Gaussian Random Number Generation: A Survey on Hardware Architectures.\" ACM Computing Surveys, 2016."),
  ref("G. E. P. Box, M. E. Muller. \"A Note on the Generation of Random Normal Deviates.\" The Annals of Mathematical Statistics, vol. 29, no. 2, 1958."),
  ref("J. Cortez et al. \"Noise generator by free FPGA technology.\" Universidad y Ciencia de la Tecnología (UCT), 2024."),
);
