%% fr_rom_gen.m — Generate Fr(s) ROM Coefficients (Boutillon ICECS'00)
%
% Theo Boutillon, công thức:
%   Fr(s) = round(2^m · f((s + δ)/16^r))    if s > 0
%   Fr(0) = 0
%
% với:
%   f(x) = √(-ln(x))     (Box-Muller radial function — Boutillon eq.(1))
%   r = 1..K     (partition level)
%   s = 0..15    (sub-segment index)
%   m = 7        (fraction bits)
%   δ = 0.467    (offset)
%   K = 5        (number of levels)
%
% Tổng ROM size: K × 16 × (2+m) bits = 5 × 16 × 9 = 720 bits = 90 bytes
%
% TẠI SAO recursive partition: xem design_decisions.md §5
%
% Output:
%   - fr_table.txt  (Verilog $readmemh format)
%   - fr_table.mat  (MATLAB binary, dùng trong fixed_model)
%
% Author: [Tên bạn]
% Date:   2026-05-20

function [fr_table, info] = fr_rom_gen()

    %% Parameters (theo Boutillon Table 1)
    K     = 5;        % partition levels
    m     = 7;        % fraction bits
    delta = 0.467;    % offset
    
    info.K = K;
    info.m = m;
    info.delta = delta;
    info.word_bits = 2 + m;     % 2 integer + m fraction
    info.total_bits = K * 16 * info.word_bits;
    
    %% Compute table
    fr_table = zeros(K, 16);     % K levels × 16 sub-segments
    fr_table_float = zeros(K, 16);  % unquantized for debug
    
    fprintf('Computing Fr(s) ROM table...\n');
    fprintf('  K=%d, m=%d, δ=%.3f, word_bits=%d\n\n', K, m, delta, info.word_bits);
    
    for r = 1:K
        for s = 0:15
            if s == 0
                fr_table(r, s+1) = 0;
                fr_table_float(r, s+1) = 0;
            else
                x = (s + delta) / (16^r);
                f_val = sqrt(-log(x));   % FIX: Boutillon eq.(1) dùng sqrt(-ln x),
                                         % vì G đã có hệ số sqrt(2). Trước đây dùng
                                         % sqrt(-2 ln x) khiến output std = sqrt(2).
                
                fr_table_float(r, s+1) = f_val;
                fr_table(r, s+1) = round_half_up(2^m * f_val);
            end
        end
    end
    
    info.max_value = max(fr_table(:));
    info.min_value = min(fr_table(:));
    info.required_bits = ceil(log2(info.max_value + 1));
    
    %% Display table
    fprintf('Fr(s) Table — Quantized (integer values):\n');
    fprintf('         ');
    for s = 0:15
        fprintf('  s=%2d ', s);
    end
    fprintf('\n');
    fprintf('         %s\n', repmat('-------', 1, 16));
    for r = 1:K
        fprintf('  r=%d   ', r);
        fprintf(' %5d ', fr_table(r, :));
        fprintf('\n');
    end
    
    fprintf('\n  Max value: %d (need %d bits)\n', info.max_value, info.required_bits);
    fprintf('  Word width: %d bits (2 integer + %d fraction)\n', info.word_bits, m);
    fprintf('  Total ROM: %d bytes\n', info.total_bits / 8);
    
    %% Plot for sanity check
    figure('Name', 'Fr ROM Coefficients');
    subplot(2,1,1);
    semilogy(1:K, fr_table_float(:, end), 'bo-', 'LineWidth', 1.5);
    hold on;
    semilogy(1:K, fr_table(:, end) / 2^m, 'rx--', 'LineWidth', 1.5);
    xlabel('Partition level r');
    ylabel('Fr(15) value (log scale)');
    title('Fr value at s=15 vs level (float vs quantized)');
    legend('Float', 'Quantized', 'Location', 'best');
    grid on;
    
    subplot(2,1,2);
    plot(0:15, fr_table_float', '-', 'LineWidth', 1);
    hold on;
    plot(0:15, fr_table' / 2^m, '--', 'LineWidth', 1);
    xlabel('Sub-segment s');
    ylabel('Fr(s) value');
    title('Fr curves for r=1..5 (lower = closer to x=0)');
    legend(arrayfun(@(r) sprintf('r=%d float', r), 1:K, 'UniformOutput', false));
    grid on;
    
    %% Save .mat for MATLAB use
    save('fr_table.mat', 'fr_table', 'info');
    fprintf('\n✓ Đã lưu fr_table.mat\n');
    
    %% Save .txt for Verilog $readmemh
    output_path = fullfile('..', '..', 'rtl', 'src', 'fr_table.txt');
    fid = fopen(output_path, 'w');
    if fid == -1
        warning('Không thể ghi vào %s, ghi vào thư mục hiện tại', output_path);
        fid = fopen('fr_table.txt', 'w');
        output_path = 'fr_table.txt';
    end
    
    fprintf(fid, '// Fr(s) ROM table — Auto-generated by fr_rom_gen.m\n');
    fprintf(fid, '// Generated: %s\n', datestr(now));
    fprintf(fid, '// Format: K=%d levels x 16 entries, %d bits per word\n', K, info.word_bits);
    fprintf(fid, '// Layout: row-major (r=1 first 16 entries, r=2 next 16, ...)\n');
    fprintf(fid, '// Verilog: initial $readmemh("fr_table.txt", fr_rom);\n');
    fprintf(fid, '//\n');
    fprintf(fid, '// r | s=0..15\n');
    
    hex_digits = ceil(info.word_bits / 4);   % hex chars cần (e.g., 9-bit → 3 hex)
    fmt = sprintf('%%0%dX', hex_digits);
    
    for r = 1:K
        fprintf(fid, '// r=%d:\n', r);
        for s = 0:15
            fprintf(fid, [fmt '\n'], fr_table(r, s+1));
        end
    end
    fclose(fid);
    fprintf('✓ Đã lưu %s (%d entries)\n', output_path, K*16);
end

%--------------------------------------------------------------------
function y = round_half_up(x)
    y = floor(x + 0.5);
end
