%% g_rom_gen.m — Generate G(s') ROM Coefficients (Boutillon ICECS'00)
%
% Theo Boutillon, công thức:
%   G(s') = round(2^m' · √2 · cos(π·(s' + δ')/512))
%
% với:
%   s' = 0..255   (8-bit index)
%   m' = 7        (fraction bits)
%   δ' = 0.5      (offset)
%
% Note: √2 multiplier để max output ≈ √2 (=181 ở dạng integer Q1.7),
% cần (1 sign + 1 int + m') = 9 bits signed (KHÔNG phải 8 — vì 181 > 127).
% (Hệ số √2 này kết hợp với Fr ROM = √(-ln x) sẽ tạo ra Box-Muller std=1.)
%
% Tổng ROM size: 256 × 9 bits = 288 bytes
%
% TẠI SAO chỉ 256 entries: xem design_decisions.md §6
%
% Output:
%   - g_table.txt  (Verilog $readmemh format)
%   - g_table.mat  (MATLAB binary)
%
% Author: [Tên bạn]
% Date:   2026-05-20

function [g_table, info] = g_rom_gen()

    %% Parameters (theo Boutillon Table 1)
    m_prime     = 7;       % fraction bits
    delta_prime = 0.5;     % offset
    N_ENTRIES   = 256;     % 8-bit index range
    
    info.m_prime = m_prime;
    info.delta_prime = delta_prime;
    info.n_entries = N_ENTRIES;
    info.word_bits = 9;   % FIX: |G|max = √2·128 = 181 > 127 nên cần 9 bit có dấu
                          % (1 sign + 1 int + m' frac). Trước đây để 1+m'=8 khiến
                          % giá trị âm bị mã hóa bù-2 sai dấu khi ghi .txt.
    info.total_bits = N_ENTRIES * info.word_bits;
    
    %% Compute table
    g_table = zeros(N_ENTRIES, 1);
    g_table_float = zeros(N_ENTRIES, 1);
    
    fprintf('Computing G(s'') ROM table...\n');
    fprintf('  m''=%d, δ''=%.1f, entries=%d, word_bits=%d\n\n', ...
            m_prime, delta_prime, N_ENTRIES, info.word_bits);
    
    for s_prime = 0:(N_ENTRIES-1)
        % G(s') = √2 · cos(π·(s'+δ')/512)
        angle = pi * (s_prime + delta_prime) / 512;
        val = sqrt(2) * cos(angle);
        
        g_table_float(s_prime + 1) = val;
        g_table(s_prime + 1) = round_half_up(2^m_prime * val);
    end
    
    info.max_value = max(g_table);
    info.min_value = min(g_table);
    info.required_bits = ceil(log2(max(abs(g_table)) + 1)) + 1;   % +1 cho sign
    
    %% Display sample entries
    fprintf('G(s'') Table sample entries:\n');
    fprintf('   s''  |    angle (rad)   |  G_float  |  G_quantized\n');
    fprintf('   ----+------------------+-----------+--------------\n');
    sample_idx = [0, 31, 63, 127, 191, 255];
    for i = sample_idx
        angle = pi * (i + delta_prime) / 512;
        fprintf('  %4d | %.4f          | %+.4f   |  %+4d\n', ...
                i, angle, g_table_float(i+1), g_table(i+1));
    end
    
    fprintf('\n  Range: [%d, %d]\n', info.min_value, info.max_value);
    fprintf('  Word width: %d bits (1 sign + %d fraction)\n', info.word_bits, m_prime);
    fprintf('  Total ROM: %d bytes\n', info.total_bits / 8);
    
    %% Plot
    figure('Name', 'G ROM Coefficients');
    subplot(2,1,1);
    plot(0:255, g_table_float, 'b-', 'LineWidth', 1.5);
    hold on;
    plot(0:255, g_table / 2^m_prime, 'r--', 'LineWidth', 1);
    xlabel('s'''); ylabel('G value');
    title('G(s'') = √2·cos(π(s''+0.5)/512)');
    legend('Float', 'Quantized', 'Location', 'best');
    grid on;
    
    subplot(2,1,2);
    err = g_table_float - g_table / 2^m_prime;
    plot(0:255, err * 2^m_prime, 'k-');
    xlabel('s'''); ylabel('Quantization error (LSB units)');
    title('Quantization error (in LSB)');
    grid on;
    
    %% Save .mat
    save('g_table.mat', 'g_table', 'info');
    fprintf('\n✓ Đã lưu g_table.mat\n');
    
    %% Save .txt for Verilog
    output_path = fullfile('..', '..', 'rtl', 'src', 'g_table.txt');
    fid = fopen(output_path, 'w');
    if fid == -1
        warning('Không thể ghi vào %s, ghi vào thư mục hiện tại', output_path);
        fid = fopen('g_table.txt', 'w');
        output_path = 'g_table.txt';
    end
    
    fprintf(fid, '// G(s'') ROM table — Auto-generated by g_rom_gen.m\n');
    fprintf(fid, '// Generated: %s\n', datestr(now));
    fprintf(fid, '// Format: %d entries, %d bits signed (2''s complement)\n', ...
            N_ENTRIES, info.word_bits);
    fprintf(fid, '// Verilog: initial $readmemh("g_table.txt", g_rom);\n');
    fprintf(fid, '//\n');
    
    hex_digits = ceil(info.word_bits / 4);
    fmt = sprintf('%%0%dX', hex_digits);
    
    for i = 1:N_ENTRIES
        % 2's complement for negative values
        val = g_table(i);
        if val < 0
            val_unsigned = val + 2^info.word_bits;
        else
            val_unsigned = val;
        end
        fprintf(fid, [fmt '   // s''=%d, G=%+d\n'], val_unsigned, i-1, g_table(i));
    end
    fclose(fid);
    fprintf('✓ Đã lưu %s (%d entries)\n', output_path, N_ENTRIES);
end

%--------------------------------------------------------------------
function y = round_half_up(x)
    if x >= 0
        y = floor(x + 0.5);
    else
        y = -floor(-x + 0.5) + (x + floor(-x + 0.5) >= 0);
        % Đảm bảo -2.5 → -2 (toward +Inf), không phải -3
        y = floor(x + 0.5);
    end
end
