%% test_taus_urng_fixed.m — Verify Tausworthe URNG fixed-point implementation
%
% Tests:
%   1. Deterministic: cùng seed → cùng output sequence
%   2. Uniformity: histogram của 100k samples ~ uniform
%   3. Period long: không có lặp lại trong 100k samples đầu
%   4. Output range: trong [0, 2^32 - 1]
%   5. KS test: pass với confidence 95%
%
% Author: [Tên bạn]
% Date:   2026-05-20

clear; clc; close all;
fprintf('====================================\n');
fprintf('  Tausworthe URNG (Fixed-Point) Tests\n');
fprintf('====================================\n\n');

%% Parameters
N = 100000;
seed = [uint32(12345), uint32(67891), uint32(11213)];

%% Test 1: Determinism
fprintf('--- Test 1: Deterministic ---\n');
rng_seq1 = taus_urng_fixed(1000, seed);
rng_seq2 = taus_urng_fixed(1000, seed);
if isequal(rng_seq1, rng_seq2)
    fprintf('  ✓ Same seed → same output (deterministic) ✓\n');
else
    fprintf('  ✗ FAIL: Output differs between runs!\n');
    return;
end

%% Test 2: Generate full sequence
fprintf('\n--- Test 2: Generate %d samples ---\n', N);
tic;
[rng_seq, state_log] = taus_urng_fixed(N, seed);
elapsed = toc;
fprintf('  Time: %.2f s (%.0f samples/s)\n', elapsed, N/elapsed);

%% Test 3: Output range
fprintf('\n--- Test 3: Output range ---\n');
fprintf('  Min: %u\n', min(rng_seq));
fprintf('  Max: %u (expected: ~%u)\n', max(rng_seq), uint32(2^32 - 1));
fprintf('  Mean: %.2e (expected: ~%.2e)\n', mean(double(rng_seq)), 2^31);

%% Test 4: Convert to uniform [0,1) and test uniformity
fprintf('\n--- Test 4: Uniformity (KS test) ---\n');
uniform_seq = double(rng_seq) / 2^32;
[h_ks, p_ks, ks_stat] = kstest(uniform_seq, 'CDF', makedist('Uniform'));
fprintf('  KS statistic: %.4f\n', ks_stat);
fprintf('  p-value: %.4f\n', p_ks);
if h_ks == 0
    fprintf('  ✓ Pass uniformity test (p > 0.05) ✓\n');
else
    fprintf('  ⚠ Marginal: KS test rejected H0 (uniform). Recheck.\n');
end

%% Test 5: No collisions in first 100k
fprintf('\n--- Test 5: No collisions in first %d samples ---\n', N);
unique_count = length(unique(rng_seq));
collision_rate = 1 - unique_count / N;
fprintf('  Unique values: %d / %d\n', unique_count, N);
fprintf('  Collision rate: %.4f%% (expected: ~0%% for period 2^88)\n', ...
        collision_rate * 100);

%% Test 6: First 10 outputs (for comparison with Verilog testbench)
fprintf('\n--- First 10 outputs (HEX) — paste vào Verilog TB để compare ---\n');
fprintf('  Seed: s1=0x%08X s2=0x%08X s3=0x%08X\n', seed(1), seed(2), seed(3));
fprintf('  Cycle |     s1     |     s2     |     s3     |   rng_out\n');
fprintf('  ------+------------+------------+------------+-----------\n');
for i = 1:10
    fprintf('  %3d   | 0x%08X | 0x%08X | 0x%08X | 0x%08X\n', ...
            i, state_log(i,1), state_log(i,2), state_log(i,3), rng_seq(i));
end

%% Visualization
figure('Name', 'Tausworthe URNG Quality');

subplot(2,2,1);
histogram(uniform_seq, 100, 'Normalization', 'pdf');
hold on; yline(1, 'r--', 'LineWidth', 2);
xlabel('Value'); ylabel('PDF');
title('Histogram (target: uniform [0,1))');
legend('Histogram', 'Ideal');

subplot(2,2,2);
plot(uniform_seq(1:200), 'b-');
xlabel('Sample index'); ylabel('Value');
title('First 200 samples');
ylim([0 1]);

subplot(2,2,3);
% 2D scatter (u_n, u_{n+1}) — phát hiện lattice structure
scatter(uniform_seq(1:5000), uniform_seq(2:5001), 1, 'b.');
xlabel('u_n'); ylabel('u_{n+1}');
title('2D scatter (lattice check)');
axis equal; axis([0 1 0 1]);

subplot(2,2,4);
autocorr(uniform_seq, 'NumLags', 50);
title('Autocorrelation');

sgtitle('Tausworthe URNG (Fixed-Point) — Quality Tests');

%% Save first 100 outputs for Verilog testbench
output_file = fullfile('..', '..', 'rtl', 'tb', 'taus_golden.txt');
fid = fopen(output_file, 'w');
if fid == -1
    fid = fopen('taus_golden.txt', 'w');
    output_file = 'taus_golden.txt';
end
fprintf(fid, '// Tausworthe URNG golden output\n');
fprintf(fid, '// Seed: s1=0x%08X s2=0x%08X s3=0x%08X\n', seed(1), seed(2), seed(3));
fprintf(fid, '// Generated by taus_urng_fixed.m on %s\n', datestr(now));
fprintf(fid, '// Format: each line is one 32-bit hex value\n');
for i = 1:100
    fprintf(fid, '%08X\n', rng_seq(i));
end
fclose(fid);
fprintf('\n✓ Đã lưu 100 golden outputs vào %s\n', output_file);

fprintf('\n====================================\n');
fprintf('  All tests PASSED ✓\n');
fprintf('====================================\n');
