%% golden_gen.m — Generate Golden Vectors cho RTL Co-Simulation
%
% Đây là OUTPUT QUAN TRỌNG NHẤT của fixed-point model.
% Sinh tất cả internal signals của pipeline, ghi vào file text
% để RTL testbench đọc và compare sample-by-sample.
%
% OUTPUT FILES (đặt trong rtl/tb/):
%   golden_config.txt         — metadata (seed, N, A, B, ...)
%   golden_urng.txt           — Tausworthe URNG output (hex 32-bit)
%   golden_bm.txt             — Box-Muller output (signed hex 16-bit)
%   golden_clt.txt            — CLT output (signed hex) — FINAL CHECK
%   golden_bm_debug.txt       — chi tiết từng signal trong BM pipeline
%
% Verilog testbench mẫu:
%   integer fp;
%   fp = $fopen("golden_clt.txt", "r");
%   for (i = 0; i < N_OUTPUT; i = i + 1) begin
%       $fscanf(fp, "%h", expected);
%       if (clt_out !== expected) begin
%           $display("MISMATCH at %d: got %h, expected %h", i, clt_out, expected);
%       end
%   end
%
% Author: [Tên bạn]
% Date:   2026-05-20

function golden_gen(N_output, seed)

    if nargin < 1, N_output = 10000; end
    if nargin < 2, seed = [uint32(12345), uint32(67891), uint32(11213)]; end
    
    % Add path để gọi được fixed_model functions
    addpath('../fixed_model');
    
    fprintf('=========================================\n');
    fprintf('  Golden Vector Generator\n');
    fprintf('=========================================\n');
    fprintf('  N_output = %d\n', N_output);
    fprintf('  seed     = [0x%08X, 0x%08X, 0x%08X]\n', seed(1), seed(2), seed(3));
    fprintf('\n');
    
    %% Parameters
    A = 4;
    B = 6;
    N_urng = N_output * A;
    
    %% Run pipeline
    fprintf('--- Running fixed-point pipeline ---\n');
    [noise, debug] = awgn_fixed_top(N_output, seed);
    
    %% Determine output directory
    out_dir = fullfile('..', '..', 'rtl', 'tb');
    if ~exist(out_dir, 'dir')
        warning('Thư mục %s không tồn tại, dùng thư mục hiện tại', out_dir);
        out_dir = '.';
    end
    
    %% 1. Config file
    fprintf('\n--- Writing golden files to %s/ ---\n', out_dir);
    
    cfg_path = fullfile(out_dir, 'golden_config.txt');
    fid = fopen(cfg_path, 'w');
    fprintf(fid, '// Golden vector config — Auto-generated by golden_gen.m\n');
    fprintf(fid, '// Generated: %s\n', datestr(now));
    fprintf(fid, '//\n');
    fprintf(fid, '// Parameters\n');
    fprintf(fid, 'N_OUTPUT  = %d\n', N_output);
    fprintf(fid, 'N_URNG    = %d\n', N_urng);
    fprintf(fid, 'A         = %d\n', A);
    fprintf(fid, 'B         = %d\n', B);
    fprintf(fid, 'SEED1     = %08X\n', seed(1));
    fprintf(fid, 'SEED2     = %08X\n', seed(2));
    fprintf(fid, 'SEED3     = %08X\n', seed(3));
    fclose(fid);
    fprintf('  ✓ golden_config.txt\n');
    
    %% 2. URNG output
    urng_path = fullfile(out_dir, 'golden_urng.txt');
    fid = fopen(urng_path, 'w');
    for i = 1:N_urng
        fprintf(fid, '%08X\n', debug.urng_seq(i));
    end
    fclose(fid);
    fprintf('  ✓ golden_urng.txt (%d entries)\n', N_urng);
    
    %% 3. Box-Muller output (signed hex, 16-bit = 4 hex digits)
    bm_path = fullfile(out_dir, 'golden_bm.txt');
    fid = fopen(bm_path, 'w');
    for i = 1:N_urng
        val = double(debug.bm_seq(i));
        if val < 0
            val = val + 2^16;
        end
        fprintf(fid, '%04X\n', uint16(val));
    end
    fclose(fid);
    fprintf('  ✓ golden_bm.txt (%d entries)\n', N_urng);
    
    %% 4. CLT output — FINAL OUTPUT cho compare
    clt_path = fullfile(out_dir, 'golden_clt.txt');
    fid = fopen(clt_path, 'w');
    for i = 1:N_output
        val = double(noise(i));
        if val < 0
            val = val + 2^16;
        end
        fprintf(fid, '%04X\n', uint16(val));
    end
    fclose(fid);
    fprintf('  ✓ golden_clt.txt (%d entries) ← QUAN TRỌNG NHẤT\n', N_output);
    
    %% 5. Debug — chi tiết 100 sample đầu cho debug RTL
    dbg_path = fullfile(out_dir, 'golden_bm_debug.txt');
    fid = fopen(dbg_path, 'w');
    fprintf(fid, '// Box-Muller pipeline debug — first 100 samples\n');
    fprintf(fid, '// Cycle | URNG     | r | s | s'' |sgn| Fr  |  G  | P_full   | P_round | BM_out\n');
    fprintf(fid, '// ------+----------+---+---+----+---+-----+-----+----------+---------+-------\n');
    
    n_debug = min(100, N_urng);
    for i = 1:n_debug
        d = debug.bm_debug{i};
        if isempty(d), continue; end
        
        bm_signed = double(debug.bm_seq(i));
        bm_unsigned = bm_signed;
        if bm_signed < 0
            bm_unsigned = bm_signed + 2^16;
        end
        
        fprintf(fid, '%5d  | %08X | %d | %2d| %3d| %d | %3d | %+4d| %+8d | %+7d | %04X\n', ...
                i, d.urng_val, d.r, d.s, d.s_prime, d.sign_bit, ...
                d.fr_val, d.g_val, d.P_full, d.P_rounded, uint16(bm_unsigned));
    end
    fclose(fid);
    fprintf('  ✓ golden_bm_debug.txt (100 entries for debug)\n');
    
    %% 6. Also save MATLAB .mat for reload
    mat_path = fullfile(out_dir, 'golden.mat');
    save(mat_path, 'noise', 'debug', 'seed', 'N_output', 'A', 'B', '-v7.3');
    fprintf('  ✓ golden.mat (full debug info)\n');
    
    %% Summary
    fprintf('\n=========================================\n');
    fprintf('  Golden vectors generated successfully\n');
    fprintf('=========================================\n');
    fprintf('  Total files: 5 text + 1 mat\n');
    fprintf('  Output directory: %s\n', out_dir);
    fprintf('\n  Verilog testbench instructions:\n');
    fprintf('    1. $readmemh("golden_urng.txt", urng_golden);\n');
    fprintf('    2. Force URNG output = urng_golden[i] cycle by cycle\n');
    fprintf('    3. Capture clt_out, compare with golden_clt.txt\n');
    fprintf('    4. Report any mismatch with cycle number\n');
    fprintf('=========================================\n');
end
